### ISSUE TITLE
Make install bugs

### ISSUE THREAD

**Issue by rockstarbill** [cs50/spl#9]
Hey David,
When ran on Ubuntu, there are two bugs with your Makefile, when make install is run. 

```
cp build/lib/{libcs.a,spl.jar} /usr/local/lib/
chmod -R a+r /usr/local/lib/{libcs.a,spl.jar}
```

Neither of these commands run properly with the {} method of cp/chmod on multiple files. Easy to fix as the user, but I thought I would let you know!

Cheers,
Bill Long

P.S. I am loving my time in the edX cs50!

**Comment by dmalan** [comment]
Ah, thanks for catching, Bill!
